### ISSUE TITLE
How does puppeth work?

### ISSUE THREAD

**Issue by CoinClubQuincy** [XinFinOrg/XDPoSChain#168]
I'm writing a script to automate the deployment of the Test network using python and when I try to use subprocess.run() I'm only able to launch puppeth but not able to enter in new Pera meters with the code. It seems as if puppeth is it own module 

I wanted to know if someone knew how you can automate a puppeth deployment

**Comment by wjrjerome** [comment]
Hi,
Puppeth is an interactive tool from geth suite. When you call puppeth using Python's subprocess.run(), you can start it, but you're having trouble because subprocess.run() is designed for commands that run, output something, then exit. Since puppeth expects interactive input after it starts (like choosing network configurations, consensus algorithms, etc.), simply starting it with subprocess.run() won't allow you to interact further to automate the entire deployment process.

To automate puppeth deployment, you need a way to programmatically send input to puppeth and handle its output. One common approach is to use pexpect or subprocess.Popen for more complex interactions. These tools allow you to spawn a process and then interact with it by sending commands and reading responses, essentially simulating what a user would type if they were running puppeth manually.

I'm not going to go detail into this as it's not related to XDC chain itself. Please refer to the puppeth and relevant tools /package/lib documentation (e.g the pexpect) i mentioned.
