### ISSUE TITLE
XDC Private chain halted, no new blocks created

### ISSUE THREAD

**Issue by raghu0891** [XinFinOrg/XDPoSChain#264]
We started the XDC Private chain from this codebase. The chain got halted by 16th of May 2023. The /var/log/syslog file has no specific error. Could someone find and let us know the fix for this sudden 'halt' behaviour??

Sytem Specification:
RAM : 60 GB
Storgae: 1.6 T
OS: Ubuntu 20.04.6 LTS
[syslogs.tgz](https://github.com/XinFinOrg/XDPoSChain/files/11486921/syslogs.tgz)
<img width="512" alt="image" src="https://github.com/XinFinOrg/XDPoSChain/assets/4936467/c82b159c-5259-461e-b8e6-94e11ad3952e">

**Comment by gzliudan** [comment]
From your log files, I found:

- Your private network is started on 05-01 17:13:30
- The signer pn2 stops producing new block after block number 417747 and time 05-11 10:02:34
- The whole network stops producing new block after block number 467167 and time 05-14 20:33:36

It needs further troubleshooting to find the cause of this issue. If there is any new situation, I will notify you.

**Comment by gzliudan** [comment]
According to your second time log files:
- The private network is started on 05-20 01:02:12
- The signer pn3 stops producing new block after block number 7625 and time 05-20 05:16:52, not report `Committing new block` 
- The singer pn1 doesn't report `Receive future block` after block number 7626 and time 05-20 05:16:54
- The whole network stops producing new block when block number 26480 and time 05-21 12:46:00
-  The signer pn1 try to produce block 26480 after block 26479, but the chain does not allow a signer creates two continuous blocks

**Comment by raghu0891** [comment]
@gzliudan the server stopped response for the second time. Log files are sent for your reference.

**Comment by raghu0891** [comment]
@gzliudan  FYI, In 5 signer network, the master node(pn0) stopped by May 31. Other nodes from(p1-p5) are working fine till date.

**Comment by gzliudan** [comment]
The node pn0 is not signer, your private network should be healthy without pn0.

**Comment by gzliudan** [comment]
According to my test logs, the master node stops producing new block at below codes:

https://github.com/XinFinOrg/XDPoSChain/blob/master/miner/worker.go#L516-L518

```go
	if !self.announceTxs && atomic.LoadInt32(&self.mining) == 0 {
		return
	}
```

This issue requires further research.

**Comment by gzliudan** [comment]
The function `syncWithPeer` posts `StartEvent` event at start time. and post `DoneEvent` or `FailedEvent` event at exit time. 

https://github.com/XinFinOrg/XDPoSChain/blob/master/eth/downloader/downloader.go#L405-L414:

```go
func (d *Downloader) syncWithPeer(p *peerConnection, hash common.Hash, td *big.Int) (err error) {
	d.mux.Post(StartEvent{})
	defer func() {
		// reset on error
		if err != nil {
			d.mux.Post(FailedEvent{err})
		} else {
			d.mux.Post(DoneEvent{})
		}
	}()
```

The miner is stopped when it receives `StartEvent` event, then variable `self.mining` is set to 0. And the miner is started when it receives `DoneEvent` or `FailedEvent` event.

https://github.com/XinFinOrg/XDPoSChain/blob/master/miner/miner.go#L84-L126:

```go
func (self *Miner) update() {
	events := self.mux.Subscribe(downloader.StartEvent{}, downloader.DoneEvent{}, downloader.FailedEvent{})
	for ev := range events.Chan() {
		switch ev.Data.(type) {
		case downloader.StartEvent:
			atomic.StoreInt32(&self.canStart, 0)
			if self.Mining() {
				self.Stop()
				atomic.StoreInt32(&self.shouldStart, 1)
				log.Info("Mining aborted due to sync")
			}
		case downloader.DoneEvent, downloader.FailedEvent:
			shouldStart := atomic.LoadInt32(&self.shouldStart) == 1

			atomic.StoreInt32(&self.canStart, 1)
			atomic.StoreInt32(&self.shouldStart, 0)
			if shouldStart {
				self.Start(self.coinbase)
			}
		}
	}
}
```

But the function `syncWithPeer` is blocked sometimes, it only post `StartEvent` event, not exit and not post `DoneEvent` or `FailedEvent` event. This behavior makes the miner stopped for ever. When it's time to produce block, the miner exits in function `commitNewWork()` untimely, because of self.mining is 0:

https://github.com/XinFinOrg/XDPoSChain/blob/master/miner/worker.go#L516-L518

```go
	if !self.announceTxs && atomic.LoadInt32(&self.mining) == 0 {
		return
	}
```

It needs further research work on why the function `syncWithPeer` is blocked.

**Comment by raghu0891** [comment]
@gzliudan, If we are not sure about the fix, then we cannot use private chain in production. We need to be sure the issue will not re-appear.

**Comment by gzliudan** [comment]
I'm troubleshooting this issue now. The root cause is still under study. I will inform you once there is a tested fix.

**Comment by gzliudan** [comment]
This problem occurs in my test environment on Sep 2. I found [the function `processFullSyncContent`](https://github.com/XinFinOrg/XDPoSChain/blob/master/eth/downloader/downloader.go#L1328) did not return.  Maybe it's blocked by in function `processFullSyncContent`:

```go
results := d.queue.Results(true)
```

Further testing is needed to determine the root cause of the problem.

**Comment by gzliudan** [comment]
This problem occurs in my test environment on Sep 4 again. The function `processFullSyncContent ` is blocked by the line https://github.com/XinFinOrg/XDPoSChain/blob/master/eth/downloader/downloader.go#L1331:
```go
results := d.queue.Results(true)
```

And the above function `d.queue.Results` is blocked the line 
https://github.com/XinFinOrg/XDPoSChain/blob/master/eth/downloader/queue.go#L360

```go
q.active.Wait()
```

I will continue to debug this issue.

**Comment by gzliudan** [comment]
I get the root cause: `q.closed` is not protected by `q.lock` in the function `Close` 

https://github.com/XinFinOrg/XDPoSChain/blob/master/eth/downloader/queue.go#L148-L151

```go
func (q *queue) Close() {
	q.closed = true
	q.active.Broadcast()
}
```
