### ISSUE TITLE
debug_traceBlockByNumber way too slow

### ISSUE THREAD

**Issue by tmeinlschmidt** [XinFinOrg/XDPoSChain#378]
hey, running xdc (full syncmode, gcmode archive, not mining) on multiple nodes. We're experiencing weird issue with `debug_traceBlockByNumber` calls.

on 24core AMD (AMD EPYC 7413 24-Core Processor) it takes almost 40secs to get the response, on 12core (Intel(R) Xeon(R) E-2386G CPU @ 3.50GHz) the same query takes 15secs. All the same version, data and configuration, we're using nvme disks.

query:
```
{
    "jsonrpc":"2.0",
        "method":"debug_traceBlockByNumber",
        "params":["0x41A0126", {"tracer": "callTracer", "timeout":"60s"}],
        "id":1
}
```
24 cores:
```
     time_namelookup:  0.000013s
        time_connect:  0.000064s
     time_appconnect:  0.000000s
    time_pretransfer:  0.000084s
       time_redirect:  0.000000s
  time_starttransfer:  33.867162s
                     ----------
          time_total:  33.867536s
```
12cores:
```
     time_namelookup:  0.000038s
        time_connect:  0.000198s
     time_appconnect:  0.000000s
    time_pretransfer:  0.000260s
       time_redirect:  0.000000s
  time_starttransfer:  15.226504s
                     ----------
          time_total:  15.226841s
```

we have issue even with these 15secs, is that a common response time?

startup (docker), using `287ca511935e0d02840ccd01651152c161ad7752` from master, tag `v2.0.0-beta1`
```
    entrypoint: XDC
    command: >
      --datadir /data
      --syncmode full
      --networkid 50
      --rpc
      --rpcwritetimeout 120s
      --rpcapi debug,eth,net,txpool,web3
      --rpcaddr 0.0.0.0
      --rpcvhosts *
      --rpcport 8545
      --ws
      --wsaddr 0.0.0.0
      --wsorigins *
      --wsport 8546
      --wsapi eth,net,txpool,web3
      --gcmode archive
      --verbosity 3
      --minerthreads 0
      --unlock <wallet hash>
      --password /data/.pwd
      --bootnodes <list of enodes>
```

Any idea about possible tuning? Saw that cache is disabled, no LRU cache, no new tracers as in geth

**Comment by gzliudan** [comment]
I will check this issue and try to cut down the execution time of debug API.

**Comment by gzliudan** [comment]
The response time is between 15 and 34 seconds according to hardware configuration and runtime load when you test. Although the response is slow, but I think it is normal. I tested your case in my VM which is 8 core and 16GB memory:

```bash
RPC="http://localhost:8545/"

NUMBER="0x41A0126"

curl -s -X POST -H "Content-Type: application/json" ${RPC} -d '{
  "jsonrpc": "2.0",
  "id": 1001,
  "method": "debug_traceBlockByNumber",
  "params": [
    "'"${NUMBER}"'", {
        "tracer":"callTracer",
        "timeout":"300s"
    }
  ]
}' | jq
```

The execution time is from 31 to 33 seconds:

```text
INFO [12-19|16:54:44] traceBlock                               block=68813094 elapsed=32.389190238s
INFO [12-19|16:58:13] traceBlock                               block=68813094 elapsed=32.507992738s
INFO [12-19|17:00:40] traceBlock                               block=68813094 elapsed=32.288445984s
INFO [12-19|17:09:07] traceBlock                               block=68813094 elapsed=31.816095439s
INFO [12-19|17:13:46] traceBlock                               block=68813094 elapsed=32.117890686s
INFO [12-19|17:14:35] traceBlock                               block=68813094 elapsed=31.987177381s
INFO [12-19|17:15:22] traceBlock                               block=68813094 elapsed=32.718815104s
INFO [12-19|17:16:08] traceBlock                               block=68813094 elapsed=32.035642261s
INFO [12-19|17:16:42] traceBlock                               block=68813094 elapsed=31.814370467s
INFO [12-19|17:17:20] traceBlock                               block=68813094 elapsed=32.808460585s
INFO [12-19|17:18:12] traceBlock                               block=68813094 elapsed=32.676524054s
```

There are some debug methods:

- debug_traceBlockByNumber
- debug_traceBlockByHash
- debug_traceBlock
- debug_traceChain

These methods are very resource-intensive, as they require the node to perform a full trace of all the transactions in a block, which can take a considerable amount of time and computational resources. So these methods result in an "execution timeout" error sometimes. 

BTW, you can fetch the traces by transaction using `debug_traceTransaction` instead of by block. This will give you the same exact data but broken up into smaller requests. This is more granular and does not require tracing all transactions in block at once.

**Comment by gzliudan** [comment]
The response time is between 15 and 34 seconds according to hardware configuration and runtime load when you test. Although the response is very slow, but I think it is normal. I also tested in my VM which is 8 core and 16GB memory:

```bash
RPC="http://localhost:8545/"

NUMBER="0x41A0126"

curl -s -X POST -H "Content-Type: application/json" ${RPC} -d '{
  "jsonrpc": "2.0",
  "id": 1001,
  "method": "debug_traceBlockByNumber",
  "params": [
    "'"${NUMBER}"'", {
        "tracer":"callTracer",
        "timeout":"300s"
    }
  ]
}' | jq
```

The execution time is from 31 to 33 seconds:

```text
INFO [12-19|16:54:44] traceBlock                               block=68813094 elapsed=32.389190238s
INFO [12-19|16:58:13] traceBlock                               block=68813094 elapsed=32.507992738s
INFO [12-19|17:00:40] traceBlock                               block=68813094 elapsed=32.288445984s
INFO [12-19|17:09:07] traceBlock                               block=68813094 elapsed=31.816095439s
INFO [12-19|17:13:46] traceBlock                               block=68813094 elapsed=32.117890686s
INFO [12-19|17:14:35] traceBlock                               block=68813094 elapsed=31.987177381s
INFO [12-19|17:15:22] traceBlock                               block=68813094 elapsed=32.718815104s
INFO [12-19|17:16:08] traceBlock                               block=68813094 elapsed=32.035642261s
INFO [12-19|17:16:42] traceBlock                               block=68813094 elapsed=31.814370467s
INFO [12-19|17:17:20] traceBlock                               block=68813094 elapsed=32.808460585s
INFO [12-19|17:18:12] traceBlock                               block=68813094 elapsed=32.676524054s
```

There are some debug methods:

- debug_traceBlockByNumber
- debug_traceBlockByHash
- debug_traceBlock
- debug_traceChain
- debug_traceTransaction

These methods are very resource-intensive, as they require the node to perform a full trace of all the transactions in a block, which can take a considerable amount of time and computational resources. So these methods result in an "execution timeout" error sometimes. 

BTW, you can fetch the traces by transaction using `debug_traceTransaction` instead of by block. This will give you the same exact data but broken up into smaller requests. This is more granular and does not require tracing all transactions in block at once.

**Comment by gzliudan** [comment]
The response time is between 15 and 34 seconds according to hardware configuration and runtime load when you test. Although the response is very slow, but I think it is normal. I also tested in my VM which is 8 core and 16GB memory:

```bash
RPC="http://localhost:8545/"

NUMBER="0x41A0126"

curl -s -X POST -H "Content-Type: application/json" ${RPC} -d '{
  "jsonrpc": "2.0",
  "id": 1001,
  "method": "debug_traceBlockByNumber",
  "params": [
    "'"${NUMBER}"'", {
        "tracer":"callTracer",
        "timeout":"300s"
    }
  ]
}' | jq
```

The execution time is from 31 to 33 seconds:

```text
INFO [12-19|16:54:44] traceBlock                               block=68813094 elapsed=32.389190238s
INFO [12-19|16:58:13] traceBlock                               block=68813094 elapsed=32.507992738s
INFO [12-19|17:00:40] traceBlock                               block=68813094 elapsed=32.288445984s
INFO [12-19|17:09:07] traceBlock                               block=68813094 elapsed=31.816095439s
INFO [12-19|17:13:46] traceBlock                               block=68813094 elapsed=32.117890686s
INFO [12-19|17:14:35] traceBlock                               block=68813094 elapsed=31.987177381s
INFO [12-19|17:15:22] traceBlock                               block=68813094 elapsed=32.718815104s
INFO [12-19|17:16:08] traceBlock                               block=68813094 elapsed=32.035642261s
INFO [12-19|17:16:42] traceBlock                               block=68813094 elapsed=31.814370467s
INFO [12-19|17:17:20] traceBlock                               block=68813094 elapsed=32.808460585s
INFO [12-19|17:18:12] traceBlock                               block=68813094 elapsed=32.676524054s
```

The debug methods are very resource-intensive, as they require the node to perform a full trace, and will take a considerable amount of time and computational resources, often result in an "execution timeout" error. 

BTW, you can fetch the traces by transaction using `debug_traceTransaction` instead of by block. This will give you the same exact data but broken up into smaller requests. This is more granular and does not require tracing all transactions in block at once.

**Comment by mszczepanik1337** [comment]
@gzliudan we tried switch to `debug_traceTransaction` but there is a lot of transactions that need 40sec+ to return traces, so i assume that is not an issue with method, more likely its setup problem.

**Comment by gzliudan** [comment]
All debug methods consume a huge amount of resources.

**Comment by mszczepanik1337** [comment]
Im just saying that switching to `debug_traceTransaction` is not a solution.

**Comment by wjrjerome** [comment]
Hi @tmeinlschmidt,

Could you provide more context or background on how you are using this API? Understanding your use case will help us prioritize the task of enhancing the performance of this particular RPC API. While we have a solution to improve the latency, it would likely only reduce it by a third and would require a significant amount of engineering effort.

Thank you in advance.

**Comment by tmeinlschmidt** [comment]
Hi,
we're providing RPC nodes for various chains, including XDC and our customers are using this feature across all the eligible chains quite heavily. Thanks

**Comment by wjrjerome** [comment]
Closing this issue as the client moved to a host with better hardware and resulted in much faster api response.

**Comment by gzliudan** [comment]
The speed is 10 times faster with PR #558:

```bash
RPC="http://localhost:8545/"

NUMBER="0x41A0126"

time curl -s -X POST -H "Content-Type: application/json" ${RPC} -d '{
  "jsonrpc": "2.0",
  "id": 1001,
  "method": "debug_traceBlockByNumber",
  "params": [
    "'"${NUMBER}"'", {
        "tracer":"callTracer",
        "timeout":"300s"
    }
  ]
}' | jq
```
